@startuml c4-deployment-diagram
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Deployment.puml

Title "Deployment Diagram"

Person(user, "User")

System_Boundary(app_stand, "App Stand"){
Container(haproxy_kc, "Keycloak Balancer", "haproxy")
Container(keycloak1, "Identity Provider", "keycloak")
Container(keycloak2, "Identity Provider", "keycloak")
Rel_D(haproxy_kc, keycloak1, "HTTP", "health-check")
Rel_D(haproxy_kc, keycloak2, "HTTP", "health-check")
BiRel_L(keycloak1, keycloak2, "TCP", "infinispan"))

Container(haproxy_db, "Database Balancer", "haproxy")

Container(pgbouncer1, "Connetction pooler", "pgbouncer")
Container(pgbouncer3, "Connetction pooler", "pgbouncer")
Container(pgbouncer2, "Connetction pooler", "pgbouncer")

Deployment_Node(node1, "Database node 1"){
    Container(postgresql1, "Database", "postgresql")
    Container(patroni1, "HA Solution", "patroni")
    Rel_L(patroni1, postgresql1, "shell", "pg_ctl, pg_basebackup, pg_rewind, psql")
}
Deployment_Node(node2, "Database node 2"){
    Container(postgresql2, "Database", "postgresql")
    Container(patroni2, "HA Solution", "patroni")
    Rel_L(patroni2, postgresql2, "shell", "pg_ctl, pg_basebackup, pg_rewind, psql")
}
Deployment_Node(node3, "Database node 3"){
    Container(postgresql3, "Database", "postgresql")
    Container(patroni3, "HA Solution", "patroni")
    Rel_L(patroni3, postgresql3, "shell", "pg_ctl, pg_basebackup, pg_rewind, psql")
}


Rel_D(keycloak1, haproxy_db, "PSQL")
Rel_D(keycloak2, haproxy_db, "PSQL")

Rel_D(haproxy_db, pgbouncer1, "PSQL")
Rel_D(haproxy_db, pgbouncer2, "PSQL")
Rel_D(haproxy_db, pgbouncer3, "PSQL")
Rel_D(haproxy_db, patroni1, "HTTP", "health-check")
Rel_D(haproxy_db, patroni2, "HTTP", "health-check")
Rel_D(haproxy_db, patroni3, "HTTP", "health-check")
Rel_D(pgbouncer1, postgresql1, "PSQL")
Rel_D(pgbouncer2, postgresql2, "PSQL")
Rel_D(pgbouncer3, postgresql3, "PSQL")

Container(consul_client1, "K/V Client", "consul")
Rel_D(patroni1,consul_client1, "HTTP")
Rel_D(patroni2,consul_client1, "HTTP")
Rel_D(patroni3,consul_client1, "HTTP")


Container(consul_server1, "K/V Server", "consul")
Container(consul_server2, "K/V Server", "consul")
Container(consul_server3, "K/V Server", "consul")

Rel(consul_client1, consul_server1, "RPC,Gossip")
Rel(consul_client1, consul_server2, "RPC,Gossip")
Rel(consul_client1, consul_server3, "RPC,Gossip")
BiRel_L(consul_server1, consul_server2, "RPC,Gossip")
BiRel_L(consul_server2, consul_server3, "RPC,Gossip")
BiRel(consul_server1, consul_server3, "RPC,Gossip")
}

Rel(user, haproxy_kc, "HTTP")
@enduml